# Generated by Django 5.1 on 2024-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/images%Y/%m/%d/'),
        ),
    ]
