# Generated by Django 5.1 on 2024-10-31 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('gender', models.CharField(choices=[('0', 'MALE'), ('1', 'FEMALE')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('description_uz', models.CharField(max_length=500, null=True)),
                ('description_ru', models.CharField(max_length=500, null=True)),
                ('description_en', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.PositiveSmallIntegerField(choices=[(0, 'Instagram'), (1, 'Telegram')], default=1)),
                ('social_media_uz', models.PositiveSmallIntegerField(choices=[(0, 'Instagram'), (1, 'Telegram')], default=1, null=True)),
                ('social_media_ru', models.PositiveSmallIntegerField(choices=[(0, 'Instagram'), (1, 'Telegram')], default=1, null=True)),
                ('social_media_en', models.PositiveSmallIntegerField(choices=[(0, 'Instagram'), (1, 'Telegram')], default=1, null=True)),
                ('link', models.URLField(max_length=255, unique=True)),
                ('link_uz', models.URLField(max_length=255, null=True, unique=True)),
                ('link_ru', models.URLField(max_length=255, null=True, unique=True)),
                ('link_en', models.URLField(max_length=255, null=True, unique=True)),
            ],
        ),
    ]
