# Generated by Django 5.1 on 2024-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uz'), ('EN', 'En'), ('RU', 'Ru')], max_length=10),
        ),
    ]
