# Generated by Django 5.1 on 2024-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_sellerdetails_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.CharField(default='asd', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='description_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellersociallink',
            name='link_en',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sellersociallink',
            name='link_ru',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sellersociallink',
            name='link_uz',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sellersociallink',
            name='social_media_en',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Instagram'), (1, 'Telegram')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='sellersociallink',
            name='social_media_ru',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Instagram'), (1, 'Telegram')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='sellersociallink',
            name='social_media_uz',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Instagram'), (1, 'Telegram')], default=1, null=True),
        ),
        migrations.DeleteModel(
            name='SellerDetails',
        ),
    ]
