# Generated by Django 5.1 on 2024-09-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_uz',
        ),
    ]
