# Generated by Django 5.1.1 on 2024-11-16 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(help_text='UZB Number +998123456789', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid phone number', regex='^\\+998\\d{9}$')])),
                ('phone2', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid phone number', regex='^\\+998\\d{9}$')])),
                ('location', models.URLField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='general/logo/image/%Y/%m/%d/')),
                ('shipping_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to='social_links/icon/image/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('UZS', 'UZS')], max_length=10)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
