# Generated by Django 5.1.1 on 2024-11-09 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
