# Generated by Django 5.1.1 on 2024-11-09 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_coupon_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='shipping',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
