# Generated by Django 5.1 on 2024-10-14 13:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='subject',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='message',
            field=models.CharField(default='', max_length=250),
        ),
    ]
