# Generated by Django 5.1 on 2024-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_total_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
