# Generated by Django 5.1.1 on 2024-11-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_category_image'),
        ('features', '0002_feature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, to='categories.category'),
        ),
    ]
