# Generated by Django 5.1.1 on 2024-11-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_alter_featurevalue_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='features.feature'),
        ),
    ]
