# Generated by Django 5.1 on 2024-10-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='rating',
        ),
    ]
