# Generated by Django 5.1 on 2024-10-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the UZS', max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feature_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_value', to='features.featurevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'feature_value')},
            },
        ),
    ]
